[bundle]
name = "Mondradiko Example World: Sponza"
compression = "LZ4"

[[assets]]
file = "model/Sponza.gltf"
initial_prefab = true

[[assets]]
file = "avatar/example-avatar.vrm"
initial_prefab = true

[[assets]]
file = "scripts/SlidingLight.wat"
alias = "SlidingLight"
environment = "AssemblyScript"

  [[assets.classes]]
  name = "SlidingLight"

[[prefabs]]
initial_prefab = true

  [prefabs.point_light]
  position = [0.0, 1.5, 0.0]
  intensity = [100.0, 0.0, 100.0]

  [prefabs.script]
  script_asset = "SlidingLight"

  [prefabs.transform]
  position = [0.0, 0.0, 0.0]

[[prefabs]]
initial_prefab = true

  [prefabs.point_light]
  position = [0.0, 1.5, 0.0]
  intensity = [0.0, 100.0, 100.0]

  [prefabs.script]
  script_asset = "SlidingLight"

  [prefabs.transform]
  position = [-3.0, 0.0, -4.0]

[[prefabs]]
initial_prefab = true

  [prefabs.point_light]
  position = [0.0, 1.5, 0.0]
  intensity = [100.0, 100.0, 0.0]

  [prefabs.script]
  script_asset = "SlidingLight"

  [prefabs.transform]
  position = [7.0, 0.0, 3.0]
